name: Continuous Deployment

on:
    workflow_dispatch:
    push:
        branches:
            - main
        paths-ignore:
            - 'README.md'
            - 'README-spirv-remap.txt'
            - 'LICENSE.txt'
            - 'CODE_OF_CONDUCT.md'
            - 'BUILD.*'
            - 'WORKSPACE'
            - 'kokoro/*'
            - 'make-revision'
            - 'Android.mk'
            - '_config.yml'

permissions: read-all

jobs:
    ios:
        name: "Build for iOS (OS64)"
        runs-on: macos-latest
        permissions:
            contents: write
        strategy:
            fail-fast: false
            matrix:
                cmake_build_type: [Debug, Release]
        steps:
            - uses: actions/checkout@v4

            - uses: lukka/get-cmake@v3.31.4

            - uses: actions/setup-python@v5
              with:
                  python-version: '3.7'

            - run: ./update_glslang_sources.py

            - name: Build
              run: |
                  mkdir build && cd build
                  cmake .. \
                    -DCMAKE_BUILD_TYPE=${{matrix.cmake_build_type}} \
                    -DCMAKE_INSTALL_PREFIX=`pwd`/install \
                    -DCMAKE_SYSTEM_NAME=iOS \
                    -DCMAKE_OSX_ARCHITECTURES=arm64 \
                    -DCMAKE_OSX_DEPLOYMENT_TARGET=11.0 \
                    -DCMAKE_OSX_SYSROOT=$(xcodebuild -version -sdk iphoneos Path)
                  make -j4 install

            - name: Test
              run: |
                  cd build
                  ctest --output-on-failure

            - name: Zip
              env:
                  ARCHIVE: glslang-main-ios-${{matrix.cmake_build_type}}.zip
              run: |
                  cd build/install
                  zip -r ${ARCHIVE} \
                      bin/glslang \
                      bin/glslangValidator \
                      include/glslang/* \
                      include/glslang/**/* \
                      lib/libGenericCodeGen.a \
                      lib/libglslang.a \
                      lib/libglslang-default-resource-limits.a \
                      lib/libMachineIndependent.a \
                      lib/libOSDependent.a \
                      lib/libSPIRV.a \
                      lib/libSPVRemapper.a \
                      lib/libSPIRV-Tools.a \
                      lib/libSPIRV-Tools-opt.a

            - name: Deploy
              env:
                  ARCHIVE: glslang-main-ios-${{matrix.cmake_build_type}}.zip
              uses: actions/github-script@v7
              with:
                  script: |
                      const script = require('.github/workflows/deploy.js')
                      await script({github, context, core})
