# NOTE: The following documentation may be useful to maintainers of this workflow.
# Github actions: https://docs.github.com/en/actions
# Github github-script action: https://github.com/actions/github-script
# GitHub REST API: https://docs.github.com/en/rest
# Octokit front-end to the GitHub REST API: https://octokit.github.io/rest.js/v18
# Octokit endpoint methods: https://github.com/octokit/plugin-rest-endpoint-methods.js/tree/master/docs/repos

name: Continuous Deployment

on:
    workflow_dispatch:
    push:
        branches:
            - main
        paths-ignore:
            - 'README.md'
            - 'README-spirv-remap.txt'
            - 'LICENSE.txt'
            - 'CODE_OF_CONDUCT.md'
            - 'BUILD.*'
            - 'WORKSPACE'
            - 'kokoro/*'
            - 'make-revision'
            - 'Android.mk'
            - '_config.yml'

permissions: read-all

jobs:
    macos:
        runs-on: macos-latest
        permissions:
            contents: write
        strategy:
            fail-fast: false
            matrix:
                os: [{genus: macos-13, family: osx}]
                compiler: [{cc: clang, cxx: clang++}]
                cmake_build_type: [Release]
        steps:
            - uses: actions/checkout@v3
            - uses: lukka/get-cmake@acb35cf920333f4dc3fc4f424f1b30d5e7d561b4 # v3.31.4
            - uses: actions/setup-python@v4
              with:
                  python-version: '3.14.0-alpha.4'
            - run: ./update_glslang_sources.py
            - name: Build for iOS (OS64)
              env:
                  CC: ${{matrix.compiler.cc}}
                  CXX: ${{matrix.compiler.cxx}}
              run: |
                  mkdir build && cd build
                  cmake .. \
                    -DCMAKE_BUILD_TYPE=${{matrix.cmake_build_type}} \
                    -DCMAKE_INSTALL_PREFIX=`pwd`/install \
                    -DCMAKE_SYSTEM_NAME=iOS \
                    -DCMAKE_OSX_ARCHITECTURES="arm64" \  # iOS device architecture (can also use "x86_64;arm64" for simulators)
                    #-DCMAKE_OSX_DEPLOYMENT_TARGET=10.5 \  # Set to a minimum supported version for iOS
                    -DCMAKE_OSX_SYSROOT=`xcodebuild -version -sdk iphoneos Path` \  # Use iOS SDK for the build
                    ..
                  make -j4 install
            - name: Test
              run: |
                  cd build
                  ctest --output-on-failure
            - name: Zip
              env:
                  ARCHIVE: glslang-main-ios-${{matrix.cmake_build_type}}.zip
              run: |
                  cd build/install
                  zip ${ARCHIVE} \
                      bin/glslang \
                      bin/glslangValidator \
                      include/glslang/* \
                      include/glslang/**/* \
                      lib/libGenericCodeGen.a \
                      lib/libglslang.a \
                      lib/libglslang-default-resource-limits.a \
                      lib/libMachineIndependent.a \
                      lib/libOSDependent.a \
                      lib/libSPIRV.a \
                      lib/libSPVRemapper.a \
                      lib/libSPIRV-Tools.a \
                      lib/libSPIRV-Tools-opt.a
            - name: Deploy
              env:
                  ARCHIVE: glslang-main-ios-${{matrix.cmake_build_type}}.zip
              uses: actions/github-script@v7.0.1
              with:
                  script: |
                      const script = require('.github/workflows/deploy.js')
                      await script({github, context, core})

